#!/bin/bash
#SBATCH --ntasks-per-node=40     # Tasks per node
#SBATCH --nodes=1                # Number of nodes requested
#SBATCH --time=2:00:00          # walltime
#SBATCH --job-name=graph_O

VASP="vasp.5.4.4.intel.std"

module load intel-mpi/2018.1.163
module load intel-compilers/2018.1.163
module load intel-mkl/2018.1.163
module load python 

echo "Running $SLURM_NTASKS processes"
echo "Run directory: $SLURM_SUBMIT_DIR"
cd $SLURM_SUBMIT_DIR

mpirun -np 40 $VASP
# export PATH=$(pwd):$PATH
# vasp-driver.pyz relax --ncpus $SLURM_NTASKS --command $VASP $SLURM_SUBMIT_DIR
